// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChl4s21YZI26CfGjZRJN7Xcl5Txu9RVnY',
    appId: '1:188395304632:web:acbf22a3b49e802dcf264d',
    messagingSenderId: '188395304632',
    projectId: 'mobile-asgm',
    authDomain: 'mobile-asgm.firebaseapp.com',
    storageBucket: 'mobile-asgm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWrW5fliWAbXitn2jr8jo23vFL3gztjcQ',
    appId: '1:188395304632:android:53cce29bdac514f7cf264d',
    messagingSenderId: '188395304632',
    projectId: 'mobile-asgm',
    storageBucket: 'mobile-asgm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvHVkG8vjugsNGOysXw7f_zivuGRrFT5g',
    appId: '1:188395304632:ios:c10f73740dcfda7ccf264d',
    messagingSenderId: '188395304632',
    projectId: 'mobile-asgm',
    storageBucket: 'mobile-asgm.firebasestorage.app',
    iosBundleId: 'com.example.mobileAssigment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvHVkG8vjugsNGOysXw7f_zivuGRrFT5g',
    appId: '1:188395304632:ios:c10f73740dcfda7ccf264d',
    messagingSenderId: '188395304632',
    projectId: 'mobile-asgm',
    storageBucket: 'mobile-asgm.firebasestorage.app',
    iosBundleId: 'com.example.mobileAssigment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChl4s21YZI26CfGjZRJN7Xcl5Txu9RVnY',
    appId: '1:188395304632:web:6105a9ad3ace2372cf264d',
    messagingSenderId: '188395304632',
    projectId: 'mobile-asgm',
    authDomain: 'mobile-asgm.firebaseapp.com',
    storageBucket: 'mobile-asgm.firebasestorage.app',
  );
}
